### ISSUE TITLE
Problem: dev guidelines lack clear PR, duration, and review instructions

### ISSUE THREAD

**Issue by angelicawill** [holdex/developers#10]
# Problem statement

The current developer guidelines isn't sufficient as the PR Requirements section doesn't provide a comprehensive guideline. There's a need for clear instructions on resolving problems via Pull Requests (PRs) for development and design problems, as well as guidelines for accurately estimating and specifying task durations in PRs or other solutions. Moreover, the guidelines also need to outline a suggested approach for handling and responding to code reviews.

### [Job story](https://miro.medium.com/max/4800/1*ua_egpJ6K1fCAQ_hY5UHAA.webp)

When: As a developer or designer working on complex projects,
I want to: have access to comprehensive and clear guidelines regarding PRs,
So I can: efficiently understand and implement best practices in solving a goal / issue by opening PRs, ensure code quality, and handling reviews.

# Proposed solution
Set up a more comprehensive guideline by revising the Solution and PR Requirements section.

**Comment by angelicawill** [comment]
@zolotokrylin Problem statement revised 😊

**Comment by zolotokrylin** [comment]
@angelicawill thank you. As you already know our process. Can you please suggest a solution in a form of PR?

**Comment by angelicawill** [comment]
@zolotokrylin I will start the PR after finishing my current task.
